# Generated by Django 3.1.4 on 2020-12-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('host', models.TextField()),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('roomId', models.TextField()),
                ('attendee', models.TextField()),
            ],
            options={
                'db_table': 'Meeting',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mail', models.TextField()),
                ('account', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
