# Generated by Django 3.1.4 on 2020-12-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='roomId',
            new_name='room',
        ),
    ]
